# Generated by Django 5.2.7 on 2025-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_organization_customuser_role_material_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='waste_date',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='waste_type',
        ),
        migrations.AlterField(
            model_name='material',
            name='cost_per_unit',
            field=models.FloatField(),
        ),
    ]
