# Generated by Django 5.2.7 on 2025-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_wasterecord_waste_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='expected_end_date',
        ),
        migrations.AddField(
            model_name='materialusage',
            name='material_supplied',
            field=models.FloatField(default=0),
        ),
    ]
