# Generated by Django 5.2.7 on 2025-10-26 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_rename_end_date_project_expected_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='storekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('engineer', 'Engineer'), ('junior_engineer', 'Junior Engineer'), ('store_keeper', 'Store Keeper'), ('surveyor', 'Surveyor'), ('manager', 'Project Manager')], max_length=50, null=True),
        ),
    ]
