# Generated by Django 5.2.7 on 2025-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_project_latitude_project_longitude_weatheralert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='materials', to='materials.project'),
        ),
    ]
