# Generated by Django 5.2.7 on 2025-12-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_remove_material_project_material_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusage',
            name='material_required',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='organization',
            field=models.ForeignKey(blank=True, default='A.T CONSTRUCTION COMPANY', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.organization'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='quantity_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, default='A.T CONSTRUCTION COMPANY', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.organization'),
        ),
    ]
