# Generated by Django 5.2.7 on 2025-12-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_materialusage_material_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusage',
            name='material',
        ),
        migrations.AddField(
            model_name='materialusage',
            name='material',
            field=models.ManyToManyField(to='materials.material'),
        ),
    ]
