# Generated by Django 5.2.7 on 2025-12-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_remove_materialusage_material_materialusage_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusage',
            name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='material_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialusage'),
        ),
    ]
