# Generated by Django 5.2.7 on 2025-12-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_remove_materialusage_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_usage',
        ),
        migrations.AddField(
            model_name='materialusage',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.material'),
        ),
    ]
