# Generated by Django 5.2.7 on 2025-12-15 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_remove_material_material_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storekeeper',
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_required', models.FloatField(default=0)),
                ('cost_per_unit', models.FloatField()),
                ('material_supplied', models.FloatField(default=0)),
                ('quantity_used', models.FloatField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.project')),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='projects', through='materials.ProjectMaterial', to='materials.material'),
        ),
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
    ]
