# Generated by Django 5.2.7 on 2025-12-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_remove_material_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterial',
            name='storekeeper',
        ),
    ]
