# Generated by Django 5.2.7 on 2025-12-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_remove_projectmaterial_storekeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='organization',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.organization'),
        ),
    ]
