# Generated by Django 5.2.7 on 2025-12-21 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_alter_material_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookAheadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('site_lead_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('site_lead_comment', models.TextField(blank=True)),
                ('procurement_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('procurement_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lookaheads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookahead', to='materials.project')),
            ],
        ),
        migrations.CreateModel(
            name='LookAheadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity_needed', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('lookahead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.lookaheadplan')),
            ],
        ),
    ]
