# Generated by Django 5.2.7 on 2025-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_lookaheadplan_lookaheaditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('admin', 'Admin'), ('engineer', 'Engineer'), ('junior_engineer', 'Junior Engineer'), ('store_keeper', 'Store Keeper'), ('surveyor', 'Surveyor'), ('manager', 'Project Manager'), ('procurement', 'Procurement')], default='pending', max_length=50),
        ),
    ]
