# Generated by Django 5.2.7 on 2025-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
