# Generated by Django 5.2.7 on 2025-12-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, default='A.T Construction Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.organization'),
        ),
    ]
